 
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){yellow} %clr(%-5level){blue} %clr([%thread]){magenta} %clr(%logger{36}){cyan} - %msg%n"
 
server:
  port: 9000
  
spring:
  profiles:
    active:
      - prod
  config:
    import: "optional:configserver:http://localhost:8071/"    
  application:
    name: cards
  datasource:
    url: jdbc:mysql://localhost:3306/cardsdb
#    driverClassName: org.h2.Driver
    username: root
    password: 1234567
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#  sql:
#    init:
#      mode: always

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"


build:
  version: 3.0

cards:
  message: "Welcome to Cards App with default profile"
  contactDetails:
    name: Default Profile
    email: default@example.com
  onCallSupport:
   - 555-555-555
   - 888-888-888

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
   
info:
  app:
    name: "cards"
    description: "Cards Application"
    version: "1.0.0"

