 
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){yellow} %clr(%-5level){blue} %clr([%thread]){magenta} %clr(%logger{36}){cyan} - %msg%n"
 
server:
  port: 9000
  
spring:
  profiles:
    active:
      - prod
  config:
    import: "optional:configserver:http://localhost:8071/"    
  application:
    name: cards
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"


#build:
#  version: 3.0
#
#cards:
#  message: "Welcome to Cards App with default profile"
#  contactDetails:
#    name: Default Profile
#    email: default@example.com
#  onCallSupport:
#   - 555-555-555
#   - 888-888-888

management:
  endpoints:
    web:
      exposure:
        include: "*"


